function newLike() {
var randomNumber = (Math.floor(Math.random()*(likes.length)));
document.getElementById('LikeDisplay').innerHTML = likes[randomNumber];
}

function newDislike() {
var randomNumber = Math.floor(Math.random()*(dislikes.length));
document.getElementById('DislikeDisplay').innerHTML = dislikes[randomNumber];
}

function userLike() {
    var yourLike = prompt('Type your like!');
    console.log(yourLike);
    alert('You like ' + yourLike + '. Good for you!');
}

function userDislike() {
    var yourDislike = prompt('Type your dislike!');
    console.log(yourDislike);
    alert('Well, ' + yourDislike + ' dislikes you too!');
}

var likes = [
    'dark chocolate',
    'milk chocolate',
    'Rolos',
    'Twix',
    'pink Starbursts',
    'ice cream',
    'Snickers',
    'rock climbing',
    'pineapple gummy bears',
    'Gushers',
    'Reeses peanut butter cups',
    'smores',
    'strawberries',
    'blueberries',
    'watermelon',
    'canteloupe',
    'nachos',
    'tangerines',
    'clementines',
    'mandarin oranges',
    'sushi',
    'orange juice',
    'mimosas',
    'crimps',
    'technical climbs',
    'slab climbs',
    'hiking',
    'predicate logic',
    'petting dogs',
    'smelling candles',
    'chocolate-dipped strawberries',
    'pineapple upside down cake',
    'smelling spices',
    'baking',
    'being productive',
    'napping',
    'folding laundry',
    'hiking',
    'karaoke',
    'paintball',
    'Tommy Caldwell',
    'Alex Honnold',
    'The Circuit Bouldering Gym',
    'sleeping in',
    'butter',
    'the fragrance of freshly baked goods',
    'having a project',
    'the smell of rain in Portland',
    'drinking coffee out of leisure rather than perceived necessity',
    'happy people',
    'eating cheese',
    'ironing clothes',
    'long drives in nice weather',
    'shooting',
    'playing board games',
    'dressing up',
    'the smell of fresh linens',
    'NW sunsets in the summer',
    'when trees transition from green to yellow, orange, and red',
    'camping',
    'being healthy',
    'kind people',
    'witty people',
    'people who than you for allowing them to change or merge into your lane',
    'rose kombucha',
    'peach kombucha',
    'ginger kombucha',
    'la croix',
    'pinot grigio',
    'cabernet sauvignon',
    'apple juice',
    'shirley temples',
    'coffee',
    'sweet tea',
    'peach ice tea',
    'raspberry lemonade',
    'strawberry lemonade',
    'strawberry limade',
    'gin',
    'green tea',
    'black tea',
    'herbal tea',
    'a fully charged laptop',
    'singing along to music in the car',
    'Bernard Williams',
    'moral philosophy',
    'friendship!',
    'cake frosting',
    'brie cheese',
    'bleu cheese',
    'manchego',
    'pasta aglio e olio',
    'getting paid',
    'chocolate oranges',
    'pain au chocolate',
    'caramel',
    'bok choy',
    'sashimi',
    'udon',
    'ramen',
    'red velvet cake',
    'cupcakes',
    'setting boulder problems in the gym',
    'topping out a scary boulder',
    'modus ponens',
    'modus tollens',
    'Tyler, the Creator',
    'Frank Ocean',
    'Two Door Cinema Club',
    'Kina Grannis',
    'Odd Future',
    'cheese and crackers',
    'Bob Ross',
    'Ruby the roadmaster (her bike)',
  ]


var dislikes = [
  'cake that falls apart',
  'bad drivers',
  'slopers',
  'Nazis',
  'National Socialism',
  'waking up early',
  'trouble kids',
  'sunburns',
  'having debt',
  'passive-aggression',
  'aggressive people',
    'confrontation',
    'beer',
    'being lied to',
    'learned helplessness',
    'giving up',
    'rejection',
    'people who do not use their signals when changing lanes or turning',
    'missing a turn',
    'traffic in hot weather',
    'winter mornings without a blanket',
    'having nightmares',
    'disappointing people',
    'salad',
    'red meat and poultry',
    'loud neighbors',
    'wasting food',
    'cats who do not let me pet them',
    'finding a spider hanging from the ceiling right before I go to sleep',
    'injuries',
    'her poor time management skils',
    'getting hungry in the middle of the night',
    'when she uses dish soap instead of dishwasher detergent in the dishwasher and everything in the world gets sudsy',
    'rotten foods',
    'mold',
    'parasites',
    'ignorance',
    'The Wheels on the Bus song',
    'heights',
  'humidity',
    'expensive rent',
    'being inaccurately judged off of an unrepresentative sample of actions',
    'pulling an all-nighter to write a paper for school',
    'getting stuck in small spaces',
    'brussel sprouts',
    'peas',
    'accidentally finding meat in her food',
    'standing for very long',
    'spending a weekend alone',
    'grape juice',
    'grape soda',
    'banana Laffy Taffy',
    'melting in hot weather',
    'hikes with many switchbacks',
    'language barriers',
    'Sleep (band)',
    'geese',
    'Death Grips',
    'Swans (band)',
    'chihuahuas',
    'tetanus',
    'expired milk',
    'eggs that end up having blood in them when she cracks them open',
    'dropping eggs',
    'gory movies',
    'when she has to yell in order to talk to somebody who is right in front of her because the area is loud',
    'impromptu public speaking',
    'spending time with somebody and not knowing whether or not it is a date',
    'people who beat around the bush instead of getting to the point for fear of hurting her feelings',
    'getting her hopes up and then being disappointed',
    'being late',
    'waiting a long time for a prescription to be filled',
    'fainting',
    'having bad breath',
    'cancer',
    'running',
    'getting her hair stuck in a zipper',
    'losing her keys',
    'losing her glasses',
    'forgetting where she parked her car',
    'when she rambles because she feels awkward and does not know when to stop',
    'kids screaming',
    'not being able to climb because she injured herself',
    'sweating',
    'butt stuff',
]
